services:
  pgvector:
    image: pgvector/pgvector:pg16
    ports:
      - 5432:5432
#    volumes:
#      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=memory2024
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres